### ISSUE TITLE
panic: runtime error: slice bounds out of range [5:0]

### ISSUE THREAD

**Issue by breezewish** [jschwinger233/grpcdump#3]
Hi, I received the following error when trying to parse a gRPC pcap:

```
panic: runtime error: slice bounds out of range [5:0]

goroutine 1 [running]:
github.com/jschwinger233/grpcdump/parser/grpcparser.(*Parser).unmarshalDataFrame(0xc000faa060, {0x91faf2, 0x11}, {0x7ffef9f150e0, 0x11}, 0xc000e9b200)
	/home/runner/work/grpcdump/grpcdump/parser/grpcparser/parser.go:180 +0x22b
github.com/jschwinger233/grpcdump/parser/grpcparser.(*Parser).Parse(0xc000faa060, {0x9c85f8, 0xc000442420})
	/home/runner/work/grpcdump/grpcdump/parser/grpcparser/parser.go:148 +0x1005
main.main.func3(0xc0002929a0)
	/home/runner/work/grpcdump/grpcdump/main.go:79 +0xd7
github.com/urfave/cli/v2.(*App).RunContext(0xc000185ba0, {0x9bc510, 0xc00003a100}, {0xc000032090, 0x9, 0x9})
	/home/runner/work/grpcdump/grpcdump/vendor/github.com/urfave/cli/v2/app.go:322 +0x7a8
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/work/grpcdump/grpcdump/vendor/github.com/urfave/cli/v2/app.go:224
```

Do you have ideas about what happened?

The pcap file is unforunately very large and containing sensitive information that I cannot upload here, but I'm willing to give helps if needed!

**Comment by jschwinger233** [comment]
Would you mind sending me the pcap using email? I'd appreciate that very much.

base64 decoded email address: Z3JleXNjaHdpbmdlckBnbWFpbC5jb20K

**Comment by breezewish** [comment]
@jschwinger233 Oh, I reproduced this error in my internal environment :)

https://transfer.sh/CjQtWc/dump.pcap
https://transfer.sh/BFUH6U/protos.tar.gz

The command I'm using with:

```
./grpcdump -p 2379 -r dump.pcap -f kvproto/proto/pdpb.proto -m AUTO

panic: runtime error: slice bounds out of range [5:0]

goroutine 1 [running]:
github.com/jschwinger233/grpcdump/parser/grpcparser.(*Parser).unmarshalDataFrame(0xc000516b40, {0x91faf2, 0x11}, {0xc0002ce7e0, 0x22}, 0xc000216f60)
	/home/runner/work/grpcdump/grpcdump/parser/grpcparser/parser.go:180 +0x22b
github.com/jschwinger233/grpcdump/parser/grpcparser.(*Parser).Parse(0xc000516b40, {0x9c85f8, 0xc0007dc840})
	/home/runner/work/grpcdump/grpcdump/parser/grpcparser/parser.go:148 +0x1005
main.main.func3(0xc00023a9a0)
	/home/runner/work/grpcdump/grpcdump/main.go:79 +0xd7
github.com/urfave/cli/v2.(*App).RunContext(0xc0000adba0, {0x9bc510, 0xc0000380b0}, {0xc000032090, 0x9, 0x9})
	/home/runner/work/grpcdump/grpcdump/vendor/github.com/urfave/cli/v2/app.go:322 +0x7a8
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/work/grpcdump/grpcdump/vendor/github.com/urfave/cli/v2/app.go:224
main.main()
	/home/runner/work/grpcdump/grpcdump/main.go:91 +0x268
```

**Comment by jschwinger233** [comment]
> @jschwinger233 Oh, I reproduced this error in my internal environment :)
> 
> https://transfer.sh/CjQtWc/dump.pcap https://transfer.sh/BFUH6U/protos.tar.gz
> 
> The command I'm using with:
> 
> ```
> ./grpcdump -p 2379 -r dump.pcap -f kvproto/proto/pdpb.proto -m AUTO
> 
> panic: runtime error: slice bounds out of range [5:0]
> 
> goroutine 1 [running]:
> github.com/jschwinger233/grpcdump/parser/grpcparser.(*Parser).unmarshalDataFrame(0xc000516b40, {0x91faf2, 0x11}, {0xc0002ce7e0, 0x22}, 0xc000216f60)
> 	/home/runner/work/grpcdump/grpcdump/parser/grpcparser/parser.go:180 +0x22b
> github.com/jschwinger233/grpcdump/parser/grpcparser.(*Parser).Parse(0xc000516b40, {0x9c85f8, 0xc0007dc840})
> 	/home/runner/work/grpcdump/grpcdump/parser/grpcparser/parser.go:148 +0x1005
> main.main.func3(0xc00023a9a0)
> 	/home/runner/work/grpcdump/grpcdump/main.go:79 +0xd7
> github.com/urfave/cli/v2.(*App).RunContext(0xc0000adba0, {0x9bc510, 0xc0000380b0}, {0xc000032090, 0x9, 0x9})
> 	/home/runner/work/grpcdump/grpcdump/vendor/github.com/urfave/cli/v2/app.go:322 +0x7a8
> github.com/urfave/cli/v2.(*App).Run(...)
> 	/home/runner/work/grpcdump/grpcdump/vendor/github.com/urfave/cli/v2/app.go:224
> main.main()
> 	/home/runner/work/grpcdump/grpcdump/main.go:91 +0x268
> ```

Will look into it in the evening, thanks.

**Comment by jschwinger233** [comment]
@breezewish Please try the latest rc release:  https://github.com/jschwinger233/grpcdump/releases/tag/v22.08.25-rc.1

BTW, I noted the enormous `data:(unknown)` output which indicates the failure of decoding grpc data bytes, and it draws my attention that parts of the parsing failure are actually linked to etcdserverpb.KV service, which ain't included in pdpb.proto.

Therefore, I made some improvements and now grpcdump accepts multiple `-f` flags such as `./grpcdump -p 2379 -r dump.pcap -f kvproto/proto/pdpb.proto -f etcd/rpc.proto -m AUTO`, and in this way multiple rpc services can be taken into account simultaneously.

Hope this change is helpful.

**Comment by breezewish** [comment]
> @breezewish Please try the latest rc release: https://github.com/jschwinger233/grpcdump/releases/tag/v22.08.25-rc.1
> 
> BTW, I noted the enormous `data:(unknown)` output which indicates the failure of decoding grpc data bytes, and it draws my attention that parts of the parsing failure are actually linked to etcdserverpb.KV service, which ain't included in pdpb.proto.
> 
> Therefore, I made some improvements and now grpcdump accepts multiple `-f` flags such as `./grpcdump -p 2379 -r dump.pcap -f kvproto/proto/pdpb.proto -f etcd/rpc.proto -m AUTO`, and in this way multiple rpc services can be taken into account simultaneously.
> 
> Hope this change is helpful.

Awesome work! The updated version successfully decoded my original large pcap file :)

Thanks a lot for your great tool!
